project:
  type: website
  output-dir: docs

website:
  title: "Nadifa's Awesome Work"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - href: projects.qmd  # <-- add this
        text: Projects   
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



